name: Python application

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]  # Correct format for the matrix strategy

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Use a specific version for consistency

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4  # Use the latest version of setup-python
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: |
        pytest
