name: Python application

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Use the latest version of actions/checkout

    - name: Set up Python 3.11
      uses: actions/setup-python@v4  # Use the latest version of actions/setup-python
      with:
        python-version: 3.11  # Specify only Python 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: |
        pytest
